# Generated by Django 3.1.3 on 2020-11-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('end_date', models.DateField(verbose_name='vigente até')),
                ('limit_subscriptions', models.IntegerField(default=0, verbose_name='limite de inscrições')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
        ),
    ]
