# Generated by Django 3.1.3 on 2021-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_auto_20201116_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='tag'),
        ),
    ]
