# Generated by Django 3.1.3 on 2022-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0003_landingpage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='to',
            field=models.CharField(default='1', max_length=10, verbose_name='Para (1 - Graduação, 2 - Pós - Graduação)'),
        ),
    ]
