# Generated by Django 3.1.3 on 2020-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='primeiro nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('celphone', models.CharField(max_length=20, verbose_name='celular')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
        ),
    ]
