# Generated by Django 3.1.3 on 2020-11-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201116_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='origin',
            new_name='landing_page',
        ),
    ]
