# Generated by Django 3.1.3 on 2020-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='aceite?'),
        ),
    ]
