# Generated by Django 3.1.3 on 2022-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201116_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='accept2',
            field=models.BooleanField(default=False, verbose_name='aceite2?'),
        ),
    ]
