# Generated by Django 3.1.3 on 2022-07-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscription_accept2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='accept',
            new_name='privacity_policy',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='accept2',
            new_name='send_offers',
        ),
    ]
