# Generated by Django 3.1.3 on 2025-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220722_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='privacity_policy',
            field=models.BooleanField(default=False, verbose_name='aceita_política?'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='send_offers',
            field=models.BooleanField(default=False, verbose_name='aceita_envio?'),
        ),
    ]
